
services:
  ollama-server:
    image: ollama/ollama
    container_name: ollama-server
    ports:
      - "${LLM_ENDPOINT_PORT:-8008}:11434"
    volumes:
      - ${OLLAMA_DATA_PATH:-./data/ollama_data}:/root/.ollama
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    
    restart: unless-stopped
    
    restart: unless-stopped
    
    restart: unless-stopped
    
  llm_text:
    build:      context: ./comps/llm_text
      dockerfile: Dockerfile
    container_name: llm_text      dockerfile: Dockerfile
      - "${LLM_TEXT_PORT:-9000}:9000"    environment:
      - LLM_ENDPOINT=${LLM_ENDPOINT}
    depends_on:
      - ollama-server
      - ./comps/llm_text:/app
      - ./comps/llm_text:/app
      - ./comps/llm_text:/app
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
      - ${LLM_XTTS_PATH:-./data/llm_xtts}:/home/llm/.xtts_data
    restart: unless-stopped
      - ${LLM_XTTS_PATH:-./data/llm_xtts}:/home/llm/.xtts_data
    restart: unless-stopped
      - ${LLM_XTTS_PATH:-./data/llm_xtts}:/home/llm/.xtts_data
    restart: unless-stopped
      - ./comps/llm_text:/app
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
      - ${LLM_XTTS_PATH:-./data/llm_xtts}:/home/llm/.xtts_data
    restart: unless-stopped

  embeddings:
    build:
      context: ./comps/embeddings
      dockerfile: Dockerfile
    container_name: embeddings
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
      - "${EMBEDDING_SERVICE_PORT:-6000}:6000"
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db




    container_name: chromadb
    volumes:
      - ${CHROMA_DATA_PATH:-./data/chroma_data}:/data
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
    container_name: chromadb
    volumes:ner_name: chromadb
    volumes:CHROMA_DATA_PATH:-./app/data/chroma_data}:/data
      - ${SHARED_DB_PATH:-./app/data/shared_db}:/app/db
    ports:
      - "${CHROMADB_PORT:-8050}:8050"
    restart: unless-stopped

  llm-vision:
    build:
      context: ./comps/llm-vision
      dockerfile: Dockerfile
    container_name: llm-vision
    ports:
      - "${LLM_VISION_PORT:-9100}:9100"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
      - ${MANGAOCR_MODELS_PATH:-./data/mangaocr_models}:/app/mangaocr_models
    volumes:
      - ./comps/llm-vision:/app
      - ${SHARED_DB_PATH:-./app/data/shared_db}:/app/db
      - ${MANGAOCR_MODELS_PATH:-./app/data/mangaocr_models}:/app/mangaocr_models
    restart: unless-stopped

  tts:
    build:
      context: ./comps/tts
      dockerfile: Dockerfile
    container_name: tts
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
      - ${TTS_DATA_PATH:-./data/tts_data}:/home/tts/.xtts_data
    volumes:
      - ./comps/tts:/app
      - ${SHARED_DB_PATH:-./app/data/shared_db}:/app/db
      - ${TTS_DATA_PATH:-./app/data/tts_data}:/home/tts/.xtts_data
    restart: unless-stopped

  asr:
    build:
      context: ./comps/asr
      dockerfile: Dockerfile
    container_name: asr
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
      - ${ASR_DATA_PATH:-./data/asr_data}:/home/asr/.xtts_data
    volumes:
      - ./comps/asr:/app
      - ${SHARED_DB_PATH:-./app/data/shared_db}:/app/db
      - ${ASR_DATA_PATH:-./app/data/asr_data}:/home/asr/.xtts_data
    restart: unless-stopped

  guardrails:
    ports:
      - "${GUARDRAILS_SERVICE_PORT:-9400}:9400"ails
      dockerfile: Dockerfile
    container_name: guardrails
      - ${SHARED_DB_PATH:-./data/shared_db}:/app/db
    ports:E_PORT:-9400}:9400"

    volumes:
      - ./comps/guardrails:/app
      - ${SHARED_DB_PATH:-./app/data/shared_db}:/app/db
    restart: unless-stopped

