# Main docker compose file

services:
  ollama-server:
    image: ollama/ollama:latest
    container_name: ollama-server
    ports:
      - "11434:11434"
    volumes:
      - ../data/ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llm_text:
    image: opea-docker-llm-text:latest
    container_name: llm_text
    ports:
      - "9000:9000"
    volumes:
      - ../data/ollama_data:/root/.ollama
      - ../data/shared_db:/app/db
    environment:
      - OLLAMA_HOST=ollama-server
    depends_on:
      - ollama-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  guardrails:
    image: opea-docker-guardrails:latest
    container_name: guardrails
    ports:
      - "9001:9001"
    volumes:
      - ../data/ollama_data:/root/.ollama
      - ../data/shared_db:/app/db
    environment:
      - OLLAMA_HOST=ollama-server
    depends_on:
      - ollama-server
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  chromadb:
    image: opea-docker-chromadb:latest
    container_name: chromadb
    ports:
      - "9002:9002"
    volumes:
      - ../data/chroma_data:/app/chromadb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  tts:
    image: opea-docker-tts:latest
    container_name: tts
    ports:
      - "9003:9003"
    volumes:
      - ../data/tts_data:/app/data/tts_data
    environment:
      - TTS_HOME=/app/data/tts_data
      - TTS_DATA_PATH=/app/data/tts_data
      - TTS_MODEL=xtts_v2
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  asr:
    image: opea-docker-asr:latest
    container_name: asr
    ports:
      - "9004:9004"
    volumes:
      - ../data/asr_data:/app/data/whisper
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  llm-vision:
    image: opea-docker-llm-vision:latest
    container_name: llm-vision
    ports:
      - "9100:9100"
    volumes:
      - ../data/mangaocr_models:/app/data/mangaocr_models
    environment:
      - MANGAOCR_MODEL_PATH=/app/data/mangaocr_models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  waifu-diffusion:
    image: opea-docker-waifu-diffusion:latest
    container_name: waifu-diffusion
    ports:
      - "9101:9101"
    volumes:
      - ../data/waifu:/app/data/waifu-diffusion
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  embeddings:
    image: opea-docker-embeddings:latest
    container_name: embeddings
    ports:
      - "9102:9102"
    volumes:
      - ../data/embeddings:/app/data/embeddings
      - ../data/shared_db:/app/db
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  default:
    name: opea-docker_default
