version: '3.8'

services:
  # Game server / API Gateway
  vn-game-server:
    build:
      context: ../server
    container_name: vn-game-server
    ports:
      - "8080:8080"
    volumes:
      - ../server:/app
      - ${SHARED_DB_PATH:-../opea-docker/data/shared_db}:/app/db
    environment:
      - OPEA_API_BASE_URL=http://opea-api-gateway:8000
      - USE_REMOTE_DB=true
    networks:
      - vn-network
      - opea-network
    restart: unless-stopped
    depends_on:
      - vn-waifu-diffusion

  # Web server for Ren'Py web export
  vn-web-server:
    image: nginx:alpine
    container_name: vn-web-server
    ports:
      - "8000:80"
    volumes:
      - ../renpy/web:/usr/share/nginx/html
    networks:
      - vn-network
    restart: unless-stopped

  # Waifu Diffusion service
  vn-waifu-diffusion:
    build:
      context: ..
      dockerfile: docker/Dockerfile.waifu
    container_name: vn-waifu-diffusion
    ports:
      - "5000:5000"
    volumes:
      - ../generated_images:/app/generated_images
      - waifu_model_cache:/app/model_cache
    environment:
      - WAIFU_DIFFUSION_MODEL=hakurei/waifu-diffusion
      - TRANSFORMERS_CACHE=/app/model_cache
      - HF_HOME=/app/model_cache
    networks:
      - vn-network
      - opea-network
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

networks:
  vn-network:
    driver: bridge
  opea-network:
    external: true
    name: opea-docker_default  # This should match your existing Docker network name

volumes:
  waifu_model_cache:  # Named volume for persisting the model cache
