services:
  # Game server / API Gateway
  vn-game-server:
    build:
      context: ../server
    container_name: vn-game-server
    ports:
      - "8080:8080"
    volumes:
      - ../server:/app
      - ${SHARED_DB_PATH:-../../opea-docker/data/shared_db}:/app/db
    environment:
      - OLLAMA_SERVER_URL=http://ollama-server:8008
      - LLM_TEXT_URL=http://llm_text:9000
      - GUARDRAILS_URL=http://guardrails:9400
      - CHROMADB_URL=http://chromadb:8050
      - TTS_URL=http://tts:9200
      - ASR_URL=http://asr:9300
      - LLM_VISION_URL=http://llm-vision:9101
      - WAIFU_DIFFUSION_URL=http://waifu-diffusion:9500
      - EMBEDDINGS_URL=http://embeddings:6000
      - USE_REMOTE_DB=true
    networks:
      - vn-network
      - opea-network
    restart: unless-stopped

  # Web server for Ren'Py web exportrver for Ren'Py web export
  vn-web-server:
    image: nginx:alpine
    container_name: vn-web-server
    ports:
      - "8000:80"
    volumes:
      - ../renpy/web:/usr/share/nginx/html
    networks:
      - vn-network
    restart: unless-stopped

  # Using opea-docker waifu-diffusion service instead of a local one

networks:
  vn-network:
    driver: bridge
  opea-network:
    external: true
    name: opea-docker_default  # This should match your existing Docker network name



